AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorkshopFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.openknowledge.sample.cloud.aws.lambda.function.HelloWorkshop
      CodeUri: ./target/myFirstLambdaFunction.jar 
      Runtime: java8
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: get
